name: Create Scaffold Project

permissions:
  contents: write
  actions: write


on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Repository name for the scaffolded project'
        required: true
        type: string
      language:
        description: 'support language'
        required: true
        type: choice
        options:
          - python
          - java
          - javascript
outputs:
  repo_url:
    description: "URL of the created repository"
    value: ${{ jobs.create-template-repository.outputs.repo_url }}

jobs:
  create-template-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository from Template
        id: create_repo
        env:
          GH_TOKEN: ${{ secrets.GH_REPO_TOKEN}}
        run: |
          gh repo create "${{ github.repository_owner }}/${{ inputs.repository_name }}" \
            --private \
            --template "${{ github.repository_owner }}/idp-template-application-${{ inputs.language }}"
           echo "repo_url=https://github.com/${{ github.repository_owner }}/${{ inputs.repository_name }}" >> "$GITHUB_OUTPUT"