name: create-self-service-aks-application

on:
  workflow_dispatch:
    inputs:
      application_properties:
        description: 'Application properties as JSON string'
        required: true
        type: string
      repository_properties:
        description: 'Application properties as JSON string'
        required: true
        type: string
      aks_namespace_properties:
        description: 'Application properties as JSON string'
        required: true
        type: string
      port_context:
        description: 'Port context as JSON string'
        required: true
        type: string
env:
    iconlist: '{"python" : "Python", "java": "Java", "javascript": "JavaScript"}'

jobs:
  create-scaffold-project:
    uses: ./templates/create-scaffold-project.yml # Path to your reusable workflow
    with:
      repository_name: ${{ fromJSON(input.repository_properties).repository_name }} 
      language: ${{ fromJSON(input.application_properties).language }}
      scaffold_required: ${{ fromJSON(input.repository_properties).scaffold_required }}
    secrets: inherit

  report-port-aks-namespace-entity:
    runs-on: ubuntu-latest
    steps:
      - name: Report to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.port.io
          operation: UPSERT
          icon: "Cluster"
          identifier: ${{ fromJSON(input.aks_namespace_properties).namespace_name }}
          blueprint: aks_namespaces
          title: ${{ fromJSON(input.aks_namespace_properties).namespace_name }}
          properties: |
            {
              "cpu_quota": "${{ fromJSON(input.aks_namespace_properties).cpu_quota }}",
              "memory_quota": "${{ fromJSON(input.aks_namespace_properties).memory_quota }}",
              "name": "${{ fromJSON(input.aks_namespace_properties).namespace_name }}"
            }
          relations: | 
            {
              "environment":  "${{ fromJSON(input.application_properties).env }}"
            }
    ## Report Port.IO stage service created #
  report-port-service:
    runs-on: ubuntu-latest
    needs: create-scaffold-project
    steps:
      - name: Report to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.port.io
          operation: UPSERT
          icon: ${{ fromJSON(env.iconlist)[inputs.language] }} 
          blueprint: ${{ fromJSON(input.port_context).action_identifier }}
          title: ${{ fromJSON(input.application_properties).application_name }}
          identifier: ${{ fromJSON(input.application_properties).application_name }}
          properties: |
            {

              "URL": "${{ needs.create-scaffold-project.outputs.repo_url }}",
              "lifecycle": "${{ fromJSON(input.application_properties).lifecycle }}",
              "language": "${{ fromJSON(input.application_properties).language }}",
            }
          relations: | 
            {
              "environment": "${{ fromJSON(input.application_properties).env }}",
              "repository": "${{ fromJSON(input.repository_properties).repository_name }}",
              "domain": "${{ fromJSON(input.port_context).domain_identifier }} ",
              aks_namespace: "${{ fromJSON(input.aks_namespace_properties).namespace_name }}",
              "application_tier": "${{ fromJSON(input.application_properties).application_tier }}"
            }