name: Provision an AKS Environment

on:
  workflow_dispatch:
    inputs:
      aks_environnment:
        description: 'Name of the AKS Environment'
        required: true
        type: string
      cpu_quota:
        description: 'Required CPU Quota for the AKS Namespace'
        required: true
        type: number
      memory_quota_gi_b:
        description: 'Required Memory Quota for the AKS Namespace'
        required: true
        type: number
      port_context:
        description: 'Port context as JSON string'
        required: true
        type: string

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: creating YAML namespace configuration
        id: create_yaml_namespace_configuration
        run: |
          echo "namespace: ${{inputs.aks_environnment}}" > namespace.yaml
          echo "cpuQuota: ${{inputs.cpu_quota}}" >> namespace.yaml
          echo "memoryQuotaGiB: ${{inputs.memory_quota_gi_b}}" >> namespace.yaml
          echo "namespace_config=$(cat namespace.yaml)" >> "$GITHUB_OUTPUT"   
      
      - name: Create Repository
        id: create_repo
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          echo "Creating repository: ${{ inputs.aks_environnment }}"

          gh repo create "${{ github.repository_owner }}/${{ inputs.aks_environnment }}" \
            --private \
            --description "${{ inputs.description }}" \
            --add-readme

          echo "repo_url=https://github.com/${{ github.repository_owner }}/${{ inputs.aks_environnment }}" >> "$GITHUB_OUTPUT"

      - name: Report to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).runId }}
          #identifier: ${{ inputs.service_name }}
          #blueprint: service
          properties: |
            {
              "github_url": "${{ steps.create_repo.outputs.repo_url }}"
            }