name: Provision an AKS Environment

on:
  workflow_dispatch:
    inputs:
      aks_environnment:
        description: 'Name of the AKS Environment'
        required: true
        type: string
      cpu_quota:
        description: 'Required CPU Quota for the AKS Namespace'
        required: true
        type: number
      memory_quota_gi_b:
        description: 'Required Memory Quota for the AKS Namespace'
        required: true
        type: number
      port_context:
        description: 'Port context as JSON string'
        required: true
        type: string

jobs:
  create-yaml-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: creating YAML namespace configuration
        id: create_yaml_namespace_configuration
        run: |
          echo "namespace: ${{inputs.aks_environnment}}" > namespace.yaml
          echo "cpuQuota: ${{inputs.cpu_quota}}" >> namespace.yaml
          echo "memoryQuotaGiB: ${{inputs.memory_quota_gi_b}}" >> namespace.yaml
          echo "namespace_config<<EOF" >> "$GITHUB_OUTPUT"
          cat namespace.yaml >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      

      - name: Report to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.port.io
          operation: UPSERT
          identifier: ${{ inputs.aks_environnment }}
          title: ${{ inputs.aks_environnment }}
          blueprint: aks_environnment
          properties: |
            {
              "repository": "${{ inputs.aks_environnment }}",
              "cpu_request": "${{ inputs.cpu_quota }}", 
              "memory_requests": "${{ inputs.memory_quota_gi_b }}",
              "cluster_name": "DEV",
              "created_at": "2025-07-21T21:11:11.298Z"
            }